//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TemplateData.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/TemplateData.xsd", IsNullable=false)]
public partial class TemplateData {
    
    private TemplateDataTemplates[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Templates")]
    public TemplateDataTemplates[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TemplateData.xsd")]
public partial class TemplateDataTemplates {
    
    private string filenameField;
    
    private string titleField;
    
    private string descriptionField;
    
    private string dateAddedField;
    
    private string packageIDField;
    
    /// <remarks/>
    public string Filename {
        get {
            return this.filenameField;
        }
        set {
            this.filenameField = value;
        }
    }
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string DateAdded {
        get {
            return this.dateAddedField;
        }
        set {
            this.dateAddedField = value;
        }
    }
    
    /// <remarks/>
    public string PackageID {
        get {
            return this.packageIDField;
        }
        set {
            this.packageIDField = value;
        }
    }
}
